DROP TABLE IF EXISTS `cloudyguy_servers`;
CREATE TABLE IF NOT EXISTS `cloudyguy_servers` (
  `MAC` varchar(18) NOT NULL,
  `TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATA` TEXT,
  PRIMARY KEY (`MAC`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;
